name: travis-test
version: "1.0"
summary: Travis test
description: Testing grounds for Travis and Snapcraft
confinement: strict

apps:
  atomify-lammps:
    command: travis-test
    plugs: [unity7, opengl, network, network-bind, home]

parts:
  environment:
    plugin: copy
    stage-packages:
      - qt573d
      - qt57charts-no-lgpl
      - qt57datavis-no-lgpl
      - qt57declarative
      - qt57graphicaleffects
      - qt57quickcontrols
      - qt57quickcontrols2
      - qt57svg
    files:
      travis-test.wrapper: bin/travis-test
