name: travis-test
version: "1.0"
summary: Travis test
description: Testing grounds for Travis and Snapcraft
confinement: strict

apps:
  atomify-lammps:
    command: travis-test
    plugs: [unity7, opengl, network, network-bind, home]

parts:
  atomify-lammps:
    source: .
    project-files:
      - atomify-lammps.pro
    qt-version: qt5
    plugin: qmake
    build-packages:
      - build-essential
      - gettext
      - intltool
      - ubuntu-touch-sounds
      - suru-icon-theme
    stage-packages:
      - ubuntu-sdk-libs
    snap:
      - -usr/share/doc
      - -usr/include
  environment:
    plugin: copy
    files:
      travis-test.wrapper: bin/travis-test
